#!/bin/bash

## Submissions helper script for INFO 1112
# Filters out unnecessary build artifacts and creates valid zip submission files

# Include only these files
include=(*.c *.cpp *.md *.sh Makefile *.sln *.vcxproj *.vcxproj.filters *.vcxproj.user)

OUTPUT_TEMPDIR="tmp"

## Helper Functions

# Copy all the files in a given directory
collect_files() {
    dir=$1
    mkdir -p "$OUTPUT_TEMPDIR"
    #cp -r "${files[@]}" "$OUTPUT_TEMPDIR"
    for f in ${files[@]}; do
        if [[ -f $f ]]; then
            echo "Including $f in submission"
            cp -rf "$f" "$OUTPUT_TEMPDIR"
        fi
    done
}

# Ensure these directories exist
if [[ ! -d $OUTPUT_TEMPDIR ]]; then
    mkdir -p $OUTPUT_TEMPDIR
fi

src=$1

# Filter all the files in the given project directory
files=${include[@]/#/${src}/}

collect_files "$OUTPUT_TEMPDIR"

# We filter out unnecessary files by globbing the results into an intermediate folder

echo "Creating submission..."
zip -r "$OUTPUT_TEMPDIR.zip" "$OUTPUT_TEMPDIR"

# Remove old tmp directory
rm -r "$OUTPUT_TEMPDIR"
