#!/bin/bash

## Submissions helper script for INFO 1112

# Include only these files
include=(*.c *.cpp *.md *.sh Makefile)

# Store zip files in submissions
OUTPUT_DIRECTORY="submissions"
OUTPUT_FILEFORMAT="${name}_${student_number}.zip"

OUTPUT_TEMPDIR="tmp"

# Read student's course personal id info
./course.sh

## Helper Functions

# Copy all the files in a given directory
collect_files() {
    dir=$1
    mkdir -p "$OUTPUT_TEMPDIR"
    #cp -r "${files[@]}" "$OUTPUT_TEMPDIR"
    for f in ${files[@]}; do
        if [[ -f $f ]]; then
            echo "Including $f in submission"
            cp -rf "$f" "$OUTPUT_TEMPDIR"
        fi
    done
}

# Ensure these directories exist
if [[ ! -d $OUTPUT_DIRECTORY ]]; then
    mkdir -p $OUTPUT_DIRECTORY
fi

if [[ ! -d $OUTPUT_TEMPDIR ]]; then
    mkdir -p $OUTPUT_TEMPDIR
fi

src=$1

# Filter all the files in the given project directory
files=${include[@]/#/${src}/}

collect_files "$OUTPUT_TEMPDIR"

# We filter out unnecessary files by globbing the results into an intermediate folder

echo "Creating submission..."
#zip -r "$OUTPUT_FILEFORMAT" "$OUTPUT_TEMPDIR"
zip -r "$OUTPUT_TEMPDIR.zip" "$OUTPUT_TEMPDIR"

rm -r "$OUTPUT_TEMPDIR"
